### ISSUE TITLE
Spring data mongodb 2.x compatibility

### ISSUE THREAD

**Issue by nicodaval** [bolcom/spring-data-mongodb-encrypt#13]
Hello,

Firstly, nice job !

When we run your module with spring boot 2.X and spring data mongo 2.X, we have an error on execution due to change from DBObject to Document in class BeforeSaveEvent :

> java.lang.NoSuchMethodError: org.springframework.data.mongodb.core.mapping.event.BeforeSaveEvent.getDBObject()Lcom/mongodb/DBObject;
> 	at com.bol.secure.EncryptionEventListener.onBeforeSave(EncryptionEventListener.java:86) ~[spring-data-mongodb-encrypt-1.2.1.jar:na]
> 	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:89) ~[spring-data-mongodb-2.0.5.RELEASE.jar:2.0.5.RELEASE]
> 	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:31) ~[spring-data-mongodb-2.0.5.RELEASE.jar:2.0.5.RELEASE]
> 

Regards

**Comment by agoston** [comment]
Indeed, I did not have the time to look into spring boot 2 yet.
Can't promise anything, first I'd like to fix all the bugs :)

Pull requests are of course welcome!

**Comment by TehBakker** [comment]
Thanks for your work!

Been using your lib on one of my project and it works great.
Sadly I wanted  to use it on a newer project that is Springboot 2 and got this issue as well.

**Comment by agoston** [comment]
I am very busy putting my spring-boot v1-based project in production right now.
One of the next steps would be to move to spring5/spring boot 2 for me too.

But if anyone has the time, feel free to fork and send a pull request!

**Comment by pltchuong** [comment]
I got CachedEncryptionEventListener works with Spring Boot 2, basically just swap all DBObject to Document, but have no time to make ReflectionEncryptionEventListener work though

**Comment by rgrebski** [comment]
I made it working by changing a bit _CachedEncryptionEventListener_ and _AbstractMongoEventListener_ here is the code:

```
public class Spring5CachedEncryptionEventListener extends AbstractEncryptionEventListener {

    @Autowired
    MongoMappingContext mappingContext;

    Map<Class, Node> encrypted;

    public Spring5CachedEncryptionEventListener(CryptVault cryptVault) {
        super(cryptVault);
    }

    @PostConstruct
    public void initReflection() {
        encrypted = new HashMap<>();

        mappingContext.getPersistentEntities().forEach(entity -> {
            List<Node> children = processDocument(entity.getType());
            if (!children.isEmpty()) encrypted.put(entity.getType(), new Node("", children, Node.Type.ROOT));
        });
    }

    @Override
    public void onAfterLoad(AfterLoadEvent event) {
        Document dbObject = event.getDocument();

        Node node = encrypted.get(event.getType());
        if (node == null) return;

        cryptFields(dbObject, node, new AbstractEncryptionEventListener.Decoder());
    }

    @Override
    public void onBeforeSave(BeforeSaveEvent event) {
        Document dbObject = event.getDocument();

        Node node = encrypted.get(event.getSource().getClass());
        if (node == null) return;

        cryptFields(dbObject, node, new AbstractEncryptionEventListener.Encoder());
    }

    void cryptFields(Document dbObject, Node node, Function<Object, Object> crypt) {
        if (node.type == Node.Type.MAP) {
            Node mapChildren = node.children.get(0);
            for (Object entry : (dbObject).values()) {
                cryptFields((Document) entry, mapChildren, crypt);
            }
            return;

        } else if (node.type == Node.Type.LIST) {
            Node mapChildren = node.children.get(0);
            for (Object entry : dbObject.entrySet()) {
                cryptFields((Document) entry, mapChildren, crypt);
            }
            return;
        }

        for (Node childNode : node.children) {
            Object value = dbObject.get(childNode.fieldName);
            if (value == null) continue;

            if (!childNode.children.isEmpty()) {
                if (value instanceof BasicDBList) {
                    for (Object o : (BasicDBList) value)
                        cryptFields((Document) o, childNode.children.get(0), crypt);
                } else {
                    cryptFields((Document) value, childNode, crypt);
                }
                return;
            }

            dbObject.put(childNode.fieldName, crypt.apply(value));
        }
    }
}
```

```
public class AbstractEncryptionEventListener extends AbstractMongoEventListener {
    protected CryptVault cryptVault;

    public AbstractEncryptionEventListener(CryptVault cryptVault) {
        this.cryptVault = cryptVault;
    }

    class Decoder extends BasicBSONDecoder implements Function<Object, Object> {
        public Object apply(Object o) {
            byte[] serialized = cryptVault.decrypt(((Binary) o).getData());
            BSONCallback bsonCallback = new AbstractEncryptionEventListener.BasicDBObjectCallback();
            decode(serialized, bsonCallback);
            BSONObject deserialized = (BSONObject) bsonCallback.get();
            return deserialized.get("");
        }
    }

    /** BasicBSONEncoder returns BasicBSONObject which makes mongotemplate converter choke :( */
    class BasicDBObjectCallback extends BasicBSONCallback {
        @Override
        public BSONObject create() {
            return new BasicDBObject();
        }

        @Override
        protected BSONObject createList() {
            return new BasicDBList();
        }

        @Override
        public BSONCallback createBSONCallback() {
            return new AbstractEncryptionEventListener.BasicDBObjectCallback();
        }
    }

    class Encoder extends BasicBSONEncoder implements Function<Object, Object> {
        public Object apply(Object o) {
            // we need to put even BSONObject and BSONList in a wrapping object before serialization, otherwise the type information is not encoded.
            // this is not particularly effective, however, it is the same that mongo driver itself uses on the wire, so it has 100% compatibility w.r.t de/serialization
            byte[] serialized = encode(new BasicBSONObject("", o));
            return new Binary(cryptVault.encrypt(serialized));
        }
    }
}
```

**Comment by agoston** [comment]
Thanks! I'm just finished with my project go-live, will pick this one up next week.

**Comment by arjunsekar1991** [comment]
Hello if by chance my encryption key is compromised what could be the way to recycle it to a new password. Please let me know if you could help with that.

**Comment by arjunsekar1991** [comment]
Also what should I do with the existing data encrypted with a key already to be re-encrypted with new key

**Comment by nOmi7** [comment]
I am facing the same problem.
@arjunsekar1991 you can encrypt with new secretkey example already provided

**Comment by agoston** [comment]
> I am facing the same problem. as @nicodaval raised.

I'll have to look into it more closely. I'd like to retain the possibility to support spring-boot 1.x too, without a fork/branch, but it's unlikely to happen.

**Comment by agoston** [comment]
Merged & released 2.0.0. Enjoy!

**Comment by Jofairden** [comment]
I'm still getting this error using 2.0.0
```
java.lang.NoSuchMethodError: org.springframework.data.mongodb.core.mapping.event.BeforeSaveEvent.getDocument()Lorg/bson/Document;`` `

**Comment by agoston** [comment]
> I'm still getting this error using 2.0.0
> 
> ```
> java.lang.NoSuchMethodError: org.springframework.data.mongodb.core.mapping.event.BeforeSaveEvent.getDocument()Lorg/bson/Document;`` `
> ```

System tests prove this work with spring-data-mongodb 2.1.0. Can you double check your actual dependencies?
